version: '3'

services:

  airflow:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ENV: "dev"
      DB_HOST: db
      DB_NAME: "airflow"
      DB_USER: "airflow"
      DB_PASSWORD: "airflow"            
    volumes:
      - ~/.aws:/usr/local/airflow/.aws
      - ~/.aws:/root/.aws
      - ./dags:/usr/local/airflow/dags
    links:
      - db

  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "airflow"
      POSTGRES_PASSWORD: "airflow"
      POSTGRES_DB: "airflow"
